# permissions for end users to edit kudus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kudu-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kudu-operator
    app.kubernetes.io/part-of: kudu-operator
    app.kubernetes.io/managed-by: kustomize
  name: kudu-editor-role
rules:
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - kudus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - kudus/status
  verbs:
  - get
