apiVersion: bigdata.kubernetesbigdataeg.org/v1alpha1
kind: Kudu
metadata:
  name: kudu-sample
spec:
  # TODO(user): edit the following value to ensure the number 
  # of Pods/Instances your Operand must have on cluster        
  masterSize: 3
  tserverSize: 4

  
